### ISSUE TITLE
in `list()` endpoint, cannot specify `metadata` with more than 1 key

### ISSUE THREAD

**Issue by keeyipatjs** [lob/lob-python#134] opened 2017-07-31 06:41 UTC
```
  # Python 3.4
  metadata = {'key1': '...', 'key2': '....'}
  results = lob.BankAccount.list(offset=0, limit=100, include=['total_count'], metadata=metadata)
  File "/usr/local/lib/python3.4/dist-packages/lob/resource.py", line 100, in list
      for key, value in params.items():
RuntimeError: dictionary changed size during iteration
```

https://github.com/lob/lob-python/blob/master/lob/resource.py#L103

**Comment by dmlittle** [comment] 2017-07-31 20:55
@keeyipatjs thanks for bringing up this issue! After looking into the issue this problem is caused by the fact that the `items()` method on a Dictionary behaves differently in py2 and py3. I've submitted a PR with a fix and I'll keep this issue open until a new version of the wrapper with this fix has been released.

**Closed** 2017-07-31 21:25 UTC

**Comment by dmlittle** [comment] 2017-07-31 21:34
A new version (3.0.1) with the fix to this issue has been released.
